site_name: ARES Documentation
nav:
    - Home: index.md
    - Installation: installation.md
    - Synthetic Generation: synth_gen.md
    - Training Classifier: training_classifier.md
    - RAG Evaluation: rag_eval.md
theme:
  name: material